# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Andrew Montecillo
title: Assistant Professor
email: admontecillo@up.edu.ph
website: https://admontecillo2023.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: andymontecillo
github_username:  admontecillo2023
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: andrew-montecillo
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0003-0627-1920

# Additional icon links
# additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Andrew, and I'm a Registered Microbiologist (Philippine Academy of Microbiology, Inc.) and I'm an Assistant Professor at the Institute of Biological Sciences, University of the Philippines Los Baños, Philippines. I also have experience in animal and plant pathogen genomics and microbial bioinformatics. I have worked at a number of research and extension projects gaining teamwork and leadership skills.

  I am most skilled in: <mark>pathogen genomics</mark>, <mark>long-reads sequencing</mark> and <mark>microbial bioinformatics</mark>

content:
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Journals and Research Articles
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  google scholar
          #  icon: fab fa-github
            url: https://scholar.google.com/citations?hl=en&authuser=1&user=Zg4bHlYAAAAJ
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          33. Lantican, NB, Barredo, G AT, Rosana, AR, Siababa, ACS, & Montecillo, AD. (2025). Draft genomes of five putative biosurfactant-producing Serratia sp. isolates from Laguna de Bay, Philippines. Microbiology Resource Announcements, e01268-24.
          
          32. Silva, BBI, Urzo, MLR, Montecillo, AD, Encabo, JR, Chuang, JP, & Chuang, KP. (2025). Retrospective detection and whole genome sequencing identify the first local case of Pigeon Rotavirus A infection in Taiwan from 2018. Scientific Reports, 15(1), 6316.

          31. Montecillo, A, Ferrer, JBC., Baybay, Z, Balmes, RM, Falconite-Cudal, R, Alba, MG, ... & Pantua, H. (2025). Two coding-complete genomes of porcine reproductive and respiratory syndrome virus 2 (PRRSV-2) from field clinical samples in the Philippines. Microbiology Resource Announcements, e01164-24.

          30. Baybay Z, Montecillo A, Pantua A, Mananggit M, Romo Jr. GR, San Pedro E, Pantua H, & Leyson CL. (2024). Molecular Characterization of a Clade 2.3.4.4b H5N1 High- Pathogenicity Avian Influenza Virus from a 2022 Outbreak in Layer Chickens in the Philippines. Pathogens 2024, 13, 844. https://doi.org/10.3390/pathogens13100844.

          29. Pajares IG, Ramos KRM, Montecillo AD, Elegado FB, & Raymundo AK. (2024). Draft genome sequence of Rhodotorula sp. BUB8, an oleaginous yeast isolated from Mt. Makiling Forest Reserve, Laguna, Philippines. Microbiology Resource Announcements, e00377-24.

          28. Datul, BB, Flores RJD, Montecillo AD, & De Leon, MP. (2024). Gut bacterial community profile of frugivorous bats from Cathedral Cave in Cavinti, Laguna, Philippines. Microbiology Resource Announcements, e00426-24.

          27. Castro AE, Montecillo AD, Villanueva RMD, & Obusan MCM. (2024). Bacterial community profiles of select tributaries of Laguna Lake in the Philippines. Microbiology Resource Announcements, 13(5), e01161-23.

          26. Silva BBI, Chen JY, Villanueva,BHA, Lu ZY, Hsing HZ, Montecillo AD, ... & Chuang KP. (2023). Genetic Diversity of Domestic Cat Hepadnavirus in Southern Taiwan. Viruses, 15(10), 2128.

          25. Vigilla-Montecillo KR, Rivera JCP, Montecillo AD, Almonte MKG, Bulao MFS, Ong JDP, & Tee ML. (2023). Awareness, knowledge, attitude, and practices (A-KAP) assessment of the One Health approach in health sciences education webinar series participants in select universities in the Philippines. Journal of Global Health Reports, 7, e2023017. 

          24. Bosito EFM, Montecillo AD, Franco RAG, Sabino NG, Bertuso ALG, Mendoza BC, & Lantican NB. (2023). Alkalihalobacillus lehensis M136, a Novel Alkaliphilic, Cyclodextrin Glucanotransferase (CGTase)-producing Isolate from Manleluag Hyperalkaline Spring in Pangasinan, Philippines. Phil J Sci,, 152(1), 109-124.

          23. Montecillo AD, Baybay Z, Cabug RC, Cariaso W, Jose JP, Mantaring S, ... & Pantua, H. (2022). Coding-Complete Genome Sequence of an African Swine Fever Virus from an Outbreak in 2021 among Domestic Pigs in Pangasinan, Philippines. Microbiol Resour Announc, 11(12), e00719-22.

          22. Villegas LC, Montecillo AD, & Leones JAM. (2022). Plant Growth Promoting Properties of a Novel Species of Rhizobium sp. Strain 11515TR Isolated from Tomato Rhizosphere in Los Baños, Laguna, Philippines. Phil J Sci, 151(3), 1099-1114.

          21. Sanchez NA, Sabino N, Montecillo AD, Fajardo, A Jr., Cervancia CR. (2021). Inhibitory Activity of Propolis from Philippine Stingless Bees (Tetragonula biroi Friese) against Select Microorganisms. Phil J Sci, 150(6A):1399-1405.

          20. Perdigon KMP, Rosana ARR, Montecillo AD, Opulencia RB, Jacildo AJ, Zulaybar TO, Raymundo AK. (2021). Genomic insights into the antimicrobial and anticancer potential of Streptomyces sp. A1-08 isolated from volcanic soils of Mount Mayon, Philippines. Phil J Sci, 150(6A):1351-1377.

          19. Elnar AG, Montecillo AD, Ilag LL, Villegas LC. (2021). Characterization of silver nanoparticles produced by wildtype and mutant Serratia marcescens Bizio. Phil Sci Letters, 14(Supplement):1-10.

          18. Verdera AB, Montecillo AD, Obusan MCM. (2021). Draft Genome Sequence of Streptomyces sp. Isolate H28 from the Meycauayan River, Philippines. Microbiol Resour Announc, 10(1): e01269-20.

          17. Montecillo AD, Ilag LL, Kohli A, Lantican NB, Raymundo AK. (2019). Archaeal community profiling of a mixed culture from mud and water slurry from a solfataric mudspring as revealed by a community proteome approach. Phil Sci Letters, 12(Supplement):1-10.

          16. Bertuso ALG, Montecillo AD, Lantican NB. (2019). Alkaline proteases from alkaliphilic and alkalitolerant bacteria from Manleluag Hyperalkaline Spring in Pangasinan, Philippines. Phil Sci Letters, 12(Supplement):81-90.

          15. Rojas SM, Rosana AR, Montecillo AD, Arboleda MD, Nacorda HM, Lantican NB. (2019). Draft genome sequences of six bacteria isolated from the Benham Bank, Philippine Rise, Philippines. Microbiol Resour Announc, 8(29):e00777-19.

          14. Franco RAG, Padalhin AR, Patrick Cuenca J, Ventura R, Montecillo A, Fernando L, Lee BT. (2019). Characterization of bacterial nanocellulose produced by isolates from Philippine nata starter and its biocompatibility. J Biomat Appl 2019 May 22:0885328219852728. 

          13. Manalang AP, Montecillo AD, Berdos LMG, Franco RAG, Bosito EFM, Sabino NG, Diaz MGQ, Lantican NB. (2019). Draft genome sequence of Bacillus lehensis M136, isolated from the Manleluag Hyperalkaline Spring in Pangasinan, Philippines. Microbiol Resour Announc, 8(13)e00029-19. DOI: 10.1128/MRA.00029-19.

          12. Mendoza RM, Baybay ZK, Fernando LM, Montecillo AD, Ilag LL, Villegas LC. (2019). Characterization of gold nanoparticles produced by biogenic synthesis using Serratia marcescens NBL1001. IOP Conference Series Earth and Environmental Science, 230:012103.

          11. Reyes A, Ambita ID, Batalon JL, Aba BL, Cortes A, Macabecha CG, Montecillo A. (2018). Isolation and characterization of keratinolytic bacteria from soil samples of poultry waste dumping sites. Int J Agric Technol, 14(7):1787-1800.

          10. Adan MFY, Baybay ZK, Lantican, NB, Fernando LM, Paterno ES, Villegas LC, Ilag LL, Montecillo AD. (2018). Silver Nanoparticles Extracellularly Produced by Serratia sp. NBL1001 have Antibacterial Properties. Phil Sci Letters, 11(2): 075-083.
          
          9. Montecillo AD, Raymundo AK, Papa IA, Aquino GMB, Jacildo AJ, Stothard P, Rosana ARR. (2018). Near-Complete Genome of Ralstonia solanacearum T523, a Phylotype I Tomato Phytopathogen Isolated from the Philippines. Microbiol Resour Announc, 7(12), e01048-18.

          8. De Leon MP, Park AY, Montecillo AD, Siringan MAT, Rosana ARR, Kim SG. (2018). Near-Complete Genome Sequences of Streptomyces sp. Strains AC1-42T and AC1-42W, Isolated from Bat Guano from Cabalyorisa Cave, Mabini, Pangasinan, Philippines. Microbiol Resour Announc, 7(7), e00904-18.

          7. Montecillo AD, Raymundo AK, Papa IA, Aquino GMB, Rosana ARR. (2018). Complete Genome Sequence of Rhizobium sp. Strain 11515TR, Isolated from Tomato Rhizosphere in the Philippines. Microbiol Resour Announc, 7(7), e00903-18.

          6. Pulido-de Leon M, Montecillo AD, Pinili DS, Siringan MAT, Park D-S. (2018). Bacterial diversity of bat guano from Cabalyorisa Cave, Mabini, Pangasinan, Philippines: A first report on the metagenome of Philippine bat guano. PLoS One, 13(7), e0200095. 

          5. Ilagan-Cruzada MFC, Rosana ARR, Montecillo AD, Sabino NG, Dalmacio IF. (2018). Complete Genome Sequence of Lactobacillus plantarum subsp. plantarum Strain LB1-2, Isolated from the Hindgut of European Honeybees, Apis mellifera L., from the Philippines. Genome announcements, 6(14), e00209-18.

          4. Cano AP, Gillado AV, Montecillo AD, Herrera MU. (2018). Copper sulfate-embedded and copper oxide-embedded filter paper and their antimicrobial properties. Mater Chem Phys 207:147-153.

          3. Grajo MRD, Villegas LC, Montecillo AD, Trinidad LC, Anarna JA, Migo VP. (2017). Effect of organic fertilizer Amina-P on the yield of pineapple (Ananas comosus L.) Merr. and soil microbial population. Philipp Agric Scientist, 100:S12-S20.

          2. Cariño SA, Montecillo AD, Atienza MTJ, Paterno ES, Ilag LL, Fernando LM. (2017). Phenotypic Characterization and Identification of Lysinibacillus sp. NBL1a Capable of Extracellular Biogenic Synthesis of Gold Nanoparticles. Philipp Agric Scientist,100:S81-S91.

          1. Montecillo AD, Sabino NG, Fajardo Jr A, Cervancia CR, Aborot ZA, Perdigon KMD, Lantican NB. (2014). Screening of lactic acid bacteria from Apis mellifera L. and Trigona spp. against Paenibacillus larvae (White) causing American Foulbrood Disease of Honeybees. Phil Entomologist, 28(1):32-42.


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Research and Journal Articles
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
